apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: greetings
spec:
  module:
    source: git::https://github.com
  organization: shridharMe
  outputs:
  - key: vpc_id
    moduleOutputName: vpc_id
  secretsMountPath: /tmp/secrets
  variables:
  - environmentVariable: true
    key: AWS_DEFAULT_REGION
    sensitive: false
    valueFrom:
      configMapKeyRef:
        key: region
        name: aws-configuration
  - environmentVariable: true
    key: CONFIRM_DESTROY
    sensitive: false
    value: '1'
